### ISSUE TITLE
Documentation broken?

### ISSUE THREAD

**Issue by whitearrowgmbh** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#1]
Hi there,

I'm not sure this problem is on my side or on yours. Since yesterday I cannot click on any of the links on your documentation page for Light Bootstrap Pro React. The only ones working are ISSUE and GO BACK TO DASHBOARD on top of the page; any details link doesn't respond.

On the console I found this error message:

![image](https://user-images.githubusercontent.com/7354771/32271770-afe3f67c-befb-11e7-92b4-8a361708ab8f.png)

pointing to this function:

![image](https://user-images.githubusercontent.com/7354771/32271830-fc20dafa-befb-11e7-9e2c-cadb4b1379bd.png)

It seems it's related to the service worker you try to establish. 

As already mentioned I'm not sure wether this problem is on my side or on yours. Could you please check it?

Thank you in advance!

**Comment by einazare** [comment]
Hi @whitearrowgmbh ,

Thank you for letting us know. We've checked this problem and it was from our side. We've made some changes in our code, and now, all the links work properly and the error doesn't exist anymore.

All the best,
Manu
