### ISSUE TITLE
Deploying on heroku

### ISSUE THREAD

**Issue by plbolduc** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#14]
Hi,

I did a project with your template and now I am trying to deploy it on Heroku.

But I have this error :

> 
> -----> React.js (create-react-app) multi app detected
> -----> Configure create-react-app build environment
>        Using `NODE_ENV=development`
> =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
> =====> Detected Framework: Multipack
> =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
> =====> Detected Framework: Node.js
> -----> Creating runtime environment
>        
>        NPM_CONFIG_LOGLEVEL=error
>        NPM_CONFIG_PRODUCTION=false
>        NODE_VERBOSE=false
>        NODE_ENV=development
>        NODE_MODULES_CACHE=true
> -----> Installing binaries
>        engines.node (package.json):  unspecified
>        engines.npm (package.json):   unspecified (use default)
>        
>        Resolving node version 8.x...
>        Downloading and installing node 8.10.0...
>        Using default npm version: 5.6.0
> -----> Restoring cache
>        Skipping cache restore (not-found)
> -----> Building dependencies
>        Installing node modules (package.json + package-lock)
>        
>        > node-sass@4.7.2 install /tmp/build_af496b1c98e9d7dca8777817671d2b50/node_modules/node-sass
>        > node scripts/install.js
>        
>        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-57_binding.node
>        Download complete
>        Binary saved to /tmp/build_af496b1c98e9d7dca8777817671d2b50/node_modules/node-sass/vendor/linux-x64-57/binding.node
>        Caching binary to /tmp/npmcache.bjHUE/node-sass/4.7.2/linux-x64-57_binding.node
>        
>        > node-sass@4.7.2 postinstall /tmp/build_af496b1c98e9d7dca8777817671d2b50/node_modules/node-sass
>        > node scripts/build.js
>        
>        Binary found at /tmp/build_af496b1c98e9d7dca8777817671d2b50/node_modules/node-sass/vendor/linux-x64-57/binding.node
>        Testing binary
>        Binary is fine
>        added 1586 packages in 43.128s
> -----> Caching build
>        Clearing previous node cache
>        Saving 2 cacheDirectories (default):
>        - node_modules
>        - bower_components (nothing to cache)
> -----> Pruning devDependencies
>        Skipping because NODE_ENV is not 'production'
> -----> Build succeeded!
> =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
> =====> Detected Framework: React.js (create-react-app)
>        Writing `static.json` to support create-react-app
>        Enabling runtime environment variables
> > entraineur-personnel-frontend@1.0.0 build /tmp/build_af496b1c98e9d7dca8777817671d2b50
> > npm run build-css && react-scripts build
> > entraineur-personnel-frontend@1.0.0 build-css /tmp/build_af496b1c98e9d7dca8777817671d2b50
> > node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/
> {
>   "status": 1,
>   "file": "/tmp/build_af496b1c98e9d7dca8777817671d2b50/src/assets/sass/light-bootstrap-dashboard.scss",
>   "line": 20,
>   "column": 1,
>   "message": "File to import not found or unreadable: lbd/plugins/animate.\nParent style sheet: /tmp/build_af496b1c98e9d7dca8777817671d2b50/src/assets/sass/light-bootstrap-dashboard.scss",
>   "formatted": "Error: File to import not found or unreadable: lbd/plugins/animate.\n       Parent style sheet: /tmp/build_af496b1c98e9d7dca8777817671d2b50/src/assets/sass/light-bootstrap-dashboard.scss\n        on line 20 of src/assets/sass/light-bootstrap-dashboard.scss\n>> @import \"lbd/plugins/animate\";\n   ^\n"
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! entraineur-personnel-frontend@1.0.0 build-css: `node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the entraineur-personnel-frontend@1.0.0 build-css script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /app/.npm/_logs/2018-03-19T22_39_58_152Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! entraineur-personnel-frontend@1.0.0 build: `npm run build-css && react-scripts build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the entraineur-personnel-frontend@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /app/.npm/_logs/2018-03-19T22_39_58_166Z-debug.log
>  !     Push rejected, failed to compile React.js (create-react-app) multi app.
>  !     Push failed
> 

Do you have any idea what it could be?

Moreover, how can I deploy on any server ? 

Thank you

**Comment by einazare** [comment]
Hello @plbolduc ,

Thank you for your interest in using our product.
From what i can see, the error comes from `scss/sass`. It seems that it doesn't find the file named `animate.scss`. 
Have you by mistake deleted it? It should be in `src/assets/sass/lbd/plugins/_animate.scss`.
Here are some tutorial on how to deploy React apps on different servers:

- [tutorial for deploying on heroku](https://blog.heroku.com/deploying-react-with-zero-configuration)
- [tutorial for deploying on github pages and surge](https://medium.freecodecamp.org/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089)
- [tutorial for deploying on S3 and CloudFront](https://medium.com/@omgwtfmarc/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af)

From this tutorial we've only tried heroku and github-pages with no errors.

If you're still having trouble with errors, do you think you could give me your archive and try to figure out what the problem is?

Best,
Manu

**Comment by plbolduc** [comment]
I just looked at the file and it seams to be there.

I just sent you a request to collaborate with my github repo, thus you will have access to the code and see what is wrong.

Meanwhile I will try another way to deploy it.

Thank you very much

**Comment by einazare** [comment]
@plbolduc , i've received your invitation. Is it ok with you if a try to deploy it on heroku to make some tests?

Manu

**Comment by einazare** [comment]
@plbolduc , at first i thought that you were missing the whole `plugins` folder from `src/assets/sass/lbd`. But then, i found that you had an `plugins/` in your gitignore. If i delete it, and if i delete line 32 `@import "lbd/plugins/_code-mirror";` from `src/assets/sass/light-bootstrap-dashboard.scss`, everything works just fine.
So, to make your app running again you need to do the following:

- delete `plugins/` from your `.gitignore` file (line 27)
- delete `@import "lbd/plugins/_code-mirror";` from `src/assets/sass/light-bootstrap-dashboard.scss` (line 32) or add a file named `_code-mirror.scss` in `src/assets/sass/lbd/plugins/`

Best,
Manu

**Comment by plbolduc** [comment]
@EINazare 
Thank tou very much for your help.
