### ISSUE TITLE
Sketch files

### ISSUE THREAD

**Issue by timworx** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#15]
Hello,
Just downloaded the files, and noticed that there is no reference to Sketch files. 

Where can I find them?

**Comment by einazare** [comment]
Hello @timworx ,

Thank you for using our product.
Can you please tell me what license have you bought?

Thank you,
Manu

**Comment by timworx** [comment]
Hi @EINazare,
Looking at the page again, I see there is a later section for licenses (that mention Sketch files specifically). 

In my purchase process, I had clicked a link to buy the Pro version, which brought me straight to checkout (no license selection).

The text on the sales page is very misleading:

```
What is in PRO Version?
Components · 60
Plugins · 13
Example Pages · 24
+ Documentation
+ SASS Files
+ Sketch Files
```

**Comment by einazare** [comment]
Hello @timworx ,

Would you like to give us your email on our platform to send you an email with a possible solution?

Best,
Manu

**Comment by AdamSchumph** [comment]
@EINazare, would I be able to get a copy of the Sketch files as well?

**Comment by einazare** [comment]
Hello @AdamSchumph ,

Unfortunately this products is comes only with PSD files.

Best,
Manu
