### ISSUE TITLE
Version 1.1.0 issue rendering Goole and FSM maps

### ISSUE THREAD

**Issue by ruegreen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#16]
Just updated to 1.1.0 version of this product and was testing the template with your sample build and notice that the Google Maps and FSM are erroring with:

Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

Havent looked closer yet but any ideas why it cannot render the sample JS for the maps?  Also, the map will display for a very very brief second and then throw this error up.

**Comment by einazare** [comment]
Hello @ruegreen ,

Have you added the API KEY for the maps?

Best,
Manu
