### ISSUE TITLE
Hello, how can I edit the style of custom form elements (checkbox, radio, etc...) ? i

### ISSUE THREAD

**Issue by sgarmendia** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#17]

**Comment by einazare** [comment]
Hello @sgarmendia ,

You can change the styles of the form elements by changing the `.scss` files.
These are the main files for the form elements (please note that there are other files that are used to style specific form elements, such as form elements in navbars):

- `src/assets/sass/lbd/_inputs.scss`
- `src/assets/sass/lbd/_forms.scss`
- `src/assets/sass/lbd/mixins/_inputs.scss`
- `src/assets/sass/lbd/_checkbox-radio-switch.scss`

Best,
Manu
