### ISSUE TITLE
Its not clear how to install and use the LBD with an existing app

### ISSUE THREAD

**Issue by joshueoconnor** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#18]
Hi,

The instructions aren't clear (when using Node) - beyond 'put the files in your project directory' and get started. How do I integrate this into an existing project? Is there a clear way to do this without having to unpick dependencies in the package.json file etc.

Can I use npm to install LBD into an existing app? Say one being built with create-react-app?

Thanks in advance

Josh

**Comment by einazare** [comment]
Hello @joshueoconnor ,

And thank you for your interest in using our product.
For you first question, unfortunately you need to unpick dependencies in the package.json file etc.
For your second and third question, we do not host this product on npmjs.

Best,
Manu.
