### ISSUE TITLE
yarn start fails with NODE_PATH not recognized on Windows

### ISSUE THREAD

**Issue by lstandifer** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#19]
D:\Users\<username>\Nextcloud\work\projects\react>cd light-dashboard-test

D:\Users\<username>\Nextcloud\work\projects\react\light-dashboard-jll>yarn start
yarn run v1.7.0
$ NODE_PATH=./src npm-run-all -p watch-css start-js
'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lstandifer** [comment]
i simply went into package.json and changed it from:

"scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "NODE_PATH=./src npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"


To: 
"scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }


and it works now 


You can now view light-bootstrap-dashboard-pro-react in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://172.26.186.193:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.



Is there any issue with doing this ?

**Comment by einazare** [comment]
Hello @lstandifer ,

Thank you for your interest in using our product.
If it works, than i believe there is no issue, but it kind of disturbs me that it works.
The thing is that we haven't used `yarn` and we do not know how to use it and can't really help you here.

Best,
Manu

**Comment by lstandifer** [comment]
It did the same thing with npm also

**Comment by claudeboueri** [comment]
After changing the script to the above i am still receiving the error : "missing script: start". I noticed you removed it from the script but with what should i replace it ?

**Comment by tarcisiopqdt** [comment]
I have the same problem

**Comment by lstandifer** [comment]
I just removed the line altogether and it finally worked

**Comment by tarcisiopqdt** [comment]
I removed the line and I have this problem now:
missing script: start :(

**Comment by scyurt** [comment]
I am having the same problem with npm, are there any solution for this?

**Comment by einazare** [comment]
Hello @scyurt ,

Please make sure you have the latest version of npm, NodeJs and our product.
If that does not do the trick, than change the start script from `"start": "NODE_PATH=./src npm-run-all -p watch-css start-js",` to `"start": "npm-run-all -p watch-css start-js",` and add a file named `.env` inside your root project folder in which you should add the following line: `NODE_PATH=./src`.

Best,
Manu

**Comment by scyurt** [comment]
Hi Manu,

Thanks for the quick response. Problem was related to Nodejs version. I've
installed the current one (v10.9), after downgrading the version to LTS
(v8), it started working.

Thanks
Sabahattin

**Comment by ashna99** [comment]
Hii  @EINazare, I am getting an issue with installing material-dashboard-react. I am a beginner and very new to React, I didn't understand where to add a file that you mentioned as ''add a file named .env inside your root project folder in which you should add the following line: NODE_PATH=./src.'' as I also tried using npm run and npm start commands after downloading files but it gave error as mentioned in the attachment. It would be a great help if anyone could help me with this.
![image](https://user-images.githubusercontent.com/53310520/105753965-7a222a00-5f6f-11eb-8a80-8a8911b785e6.png)

**Comment by lstandifer** [comment]
root of your directory is usually the directory where your package.json is located. the above areas just look like prettier doesn't like the code i would disable it until you get the app\s working.

**Comment by ashna99** [comment]
I tried installing npm and executing npm start again but still, it's giving me this long list of errors:


 Line 24:18:   Replace `input` with `(input)`  prettier/prettier
```prettier errors here```

src\assets\jss\material-dashboard-react\checkboxAdnRadioStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\buttonStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardAvatarStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardBodyStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardFooterStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardHeaderStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardIconStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\cardStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\customInputStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\customTabsStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\footerStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\headerLinksStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\headerStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\rtlHeaderLinksStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\sidebarStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\snackbarContentStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\tableStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\tasksStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\components\typographyStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\dropdownStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\layouts\adminStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\layouts\rtlStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\tooltipStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\views\dashboardStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\views\iconsStyle.js
```prettier errors here```

src\assets\jss\material-dashboard-react\views\rtlStyle.js
```prettier errors here```

src\components\Card\Card.js
```prettier errors here```

src\components\Card\CardAvatar.js
```prettier errors here```

src\components\Card\CardBody.js
```prettier errors here```

src\components\Card\CardFooter.js
```prettier errors here```

src\components\Card\CardHeader.js
```prettier errors here```

src\components\Card\CardIcon.js
```prettier errors here```

src\components\CustomButtons\Button.js
```prettier errors here```

src\components\CustomInput\CustomInput.js
```prettier errors here```

src\components\CustomTabs\CustomTabs.js
```prettier errors here```

src\components\Grid\GridContainer.js
```prettier errors here```

src\components\Grid\GridItem.js
```prettier errors here```

src\components\Navbars\AdminNavbarLinks.js
```prettier errors here```

src\components\Navbars\Navbar.js
```prettier errors here```

src\components\Navbars\RTLNavbarLinks.js
```prettier errors here```

src\components\Snackbar\Snackbar.js
```prettier errors here```

src\components\Snackbar\SnackbarContent.js
```prettier errors here```

src\components\Table\Table.js
```prettier errors here```

src\components\Tasks\Tasks.js
```prettier errors here```

src\components\Typography\Danger.js
```prettier errors here```

src\components\Typography\Info.js
```prettier errors here```

src\components\Typography\Muted.js
```prettier errors here```

src\components\Typography\Primary.js
```prettier errors here```

src\components\Typography\Quote.js
```prettier errors here```

src\components\Typography\Success.js
```prettier errors here```

src\components\Typography\Warning.js
```prettier errors here```

src\layouts\Admin.js
```prettier errors here```

src\layouts\RTL.js
```prettier errors here```

src\routes.js
```prettier errors here```

src\variables\charts.js
```prettier errors here```

src\variables\general.js
```prettier errors here```

src\views\Dashboard\Dashboard.js
```prettier errors here```

src\views\Maps\Maps.js
```prettier errors here```

src\views\TableList\TableList.js
```prettier errors here```

src\views\Typography\Typography.js
```prettier errors here```

src\views\UpgradeToPro\UpgradeToPro.js
```prettier errors here```

src\views\UserProfile\UserProfile.js
```prettier errors here```

Search for the keywords to learn more about each error.

**Comment by ashna99** [comment]
I tried downloading nodejs  latest version but during the execution of NPN install, I am getting following errors:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: material-dashboard-react@1.9.0
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.5.4" from react-google-maps@7.3.0
npm ERR! node_modules/react-google-maps
npm ERR!   react-google-maps@"^7.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ACER\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Local\npm-cache\_logs\2021-01-26T03_05_09_445Z-debug.log

**Comment by einazare** [comment]
Hello there, @ashna99 ,

Please download and install NodeJS version 14.15.4 LTS.
If that does not work, please fill in the following form with detailed steps of how to reproduce your issue: https://www.creative-tim.com/new-issue/material-dashboard-react

Best,
Manu

PS: I hope you are ok with this, but I've trimmed your comment since it was too big.
