### ISSUE TITLE
Sub-Menu

### ISSUE THREAD

**Issue by cmtehenz** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#20]
How can I make a Submenu on the sidebar?

**Comment by einazare** [comment]
Hello @cmtehenz ,

And thank you for your interest in using our products.
If you are speaking about a collapse like the one made by us, for example `Components` collapse, the this is very easy.
You just need to add some components in our routing system.
Actually we have this in our live docs, here is a link for this issue: [https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/routing-system](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/routing-system).

Best,
Manu
