### ISSUE TITLE
Help need - for select inside FormInputs

### ISSUE THREAD

**Issue by susuwatari2** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#21]
How can I use select inside FormInputs component? What should I put in properties for a select input?

**Comment by einazare** [comment]
Hello @susuwatari2 ,

And thank you for your interest in using our product.
The select has not been added to our FormInputs component. 
Actually the name should be quite intuitive - FormInputs -> Form + Inputs, meaning that only inputs are rendered in this component.
I think it would be better for you to use this component instead: [https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/customizable-select](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/customizable-select)

Best,
Manu

**Comment by susuwatari2** [comment]
I like how FormInputs component makes input into an array.
If my form contains a select and several inputs, do I need to use 
 <FormGroup>, <ControlLabel>,<FormControl>
for each of the input?

**Comment by einazare** [comment]
Hello again @susuwatari2 ,

```
If my form contains a select and several inputs, do I need to use
```
I do not understand the question, what do you need to use?

Best,
Manu

**Comment by susuwatari2** [comment]
Hello Manu,

Sorry my bad.

If I have a select and several inputs in my form, do I need to use <FormGroup>, <ControlLabel>and<FormControl> for each of the input?

**Comment by einazare** [comment]
Hello again @susuwatari2 ,

I still do not understand your question.
Just use the simple form elements from [react-bootstrap](https://react-bootstrap.github.io/components/forms/) like we've done in our [RegularForms](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/forms/regular-forms) view page (`src/views/Forms/RegularForms.jsx`).

Best,
Manu
