### ISSUE TITLE
I. am having an issue starting

### ISSUE THREAD

**Issue by ace034** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#22]
Hello creative-tim I have rerun npm install and then run the command npm start and it then when I run it, it loads the localhost:3000 and reads "To get started, edit src/App.js and save to reload." how do I fix this issue?

**Comment by einazare** [comment]
Hello there @ace034 ,

Thank you for your interest in using our product.
There must be something wrong with what you are doing.
Please read our live docs here: [https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/tutorial](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/tutorial)

Best,
Manu

**Comment by ace034** [comment]
Hello creative I am trying to use the settings configuration that you have via the live pro demo where is that configuration?

**Comment by einazare** [comment]
Hello again @ace034 ,

That plugin is only used by us to show our possible clients / users that our dashboard can be customized with different colors and images.

Best,
Manu
