### ISSUE TITLE
navigator error

### ISSUE THREAD

**Issue by Apollo725** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#24]
When I implement dashboard, I can see this error
![screen shot 2018-10-09 at 23 45 11](https://user-images.githubusercontent.com/38185119/46700541-61b26800-cc1d-11e8-9e96-faa493197d00.png)

My code is the following
![screen shot 2018-10-09 at 23 44 31](https://user-images.githubusercontent.com/38185119/46700576-7262de00-cc1d-11e8-81f9-e6ec0b0ea386.png)
How can I overcome this issue?
.

**Comment by einazare** [comment]
Hello there @Apollo725 ,

Is this still an issue?

Best,
Manu

**Comment by Apollo725** [comment]
@EINazare no, I had solved, thank you for your care.
