### ISSUE TITLE
Issue on routing system

### ISSUE THREAD

**Issue by susuwatari2** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#26]
Hi, we can do simply /path/name. 
I am working on a product list page and single product page. How does it work with your routing system?

For example:
1. product list page on the sidebar
{ path: "/products", name: "Products", icon: "icon", component: ProductList }
2. single product 
{ path: "/products/:id", component: SingleProduct }

or where should I put <Link to="/product/:id"> as react route?

Thank you.

**Comment by einazare** [comment]
Hello there @susuwatari2 ,

Thank you for your interest in working with our products.
I think you will find useful this link here: [https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/51](https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/51)
These products have the same routing system, so what has been answered there, will work on this product (light bootstrap) as well.

Hope this information helps you. Please let us know if we can be of further assistance.

Best,
Manu

**Comment by susuwatari2** [comment]
Yes, it is linking to the right product id but the page header is collapsed. 
I set invisible: true as single product page shouldn't show on nav menu.

How can I handle it?

**Comment by einazare** [comment]
> Yes, it is linking to the right product id but the page header is collapsed.
> I set invisible: true as single product page shouldn't show on nav menu.
> 
> How can I handle it?

Hello again @susuwatari2 ,

I've read your comment several times, but I think I do not fully understand your situations.
Can you please tell me what is not working as you would like?

Best,
Manu

**Comment by susuwatari2** [comment]
How can I keep the navbar-header even I am doing { path: "/products/:id", component: SingleProduct }?

**Comment by einazare** [comment]
Hello there @susuwatari2 ,

Once again I am going to ask you for more details.
A screenshot maybe would make me understand.

Best,
Manu
