### ISSUE TITLE
How can I create dynamic routes without reloading data?

### ISSUE THREAD

**Issue by duckdd7788** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#27]
Hi, 

How can I create dynamic routes without reloading data? like changing the URL without reloading the page?

I created the Breadcrumbs like items and :itemId. I had the data of items loaded on items page from an api endpoints. However, it reloads the data and refreash the state every time I go back to items page from item detail page.

**Comment by einazare** [comment]
Hello there @duckdd7788 ,

Thank you for your interest in working with our products.
I think this is caused by the fact that you have your API call inside the items page. And everytime that component is mounted, the API call is made.

Best,
Manu

**Comment by duckdd7788** [comment]
What would be your suggestion for storing the data when I am back to items page?

**Comment by einazare** [comment]
Hello again @duckdd7788 ,

I think you could use Redux.

Best,
Manu
