### ISSUE TITLE
Header and footer above sidebar and below sidebar

### ISSUE THREAD

**Issue by skgrehli** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#28]
Hi How can implement header above sidebar and footer below sidebar?

**Comment by einazare** [comment]
Hello there @skgrehli ,

Thank you for your interest in working with our products.
Unfortunately, this behavior cannot be achieved at the moment in our product.
Actually in none of our products can be achieved this.
I will take a look into the problem and see if I can find a workaround, in the meantime, any help would be much appreciated.

Best,
Manu
