### ISSUE TITLE
Checkbox changes issue

### ISSUE THREAD

**Issue by susuwatari2** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#29]
How can I update Checkbox changes and save it? Can I have a onClick function for `Checkbox`?
I have `isChecked`, but the checkbox checked returns false

**Comment by einazare** [comment]
Hello there @susuwatari2 ,

Thank you for your interest in working with our product.
Can you please detail your issue?
Are you doing some sort of POST or GET?
If so, why not add a name to your checkbox?
Something similar to:
```
<Checkbox number="1" label="Subscribe to newsletter" name="myCheck"/>
```
And when you make the POST or GET you would have `myCheck=on` if the checkbox would be checked, and you would have `myCheck=undefined` else.

Best,
Manu
