### ISSUE TITLE
how to keep footer at the bottom of the page?

### ISSUE THREAD

**Issue by MerouaneBen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#30]
I get the footer  at the middle of the page when  there just few content in the view. How can I fix the footer at the bottom of the page in this template?

thanks

**Comment by einazare** [comment]
Hello there, @MerouaneBen ,

Thank you for your interest in working with our products.
To achieve your desired effect, you need to do the following:
- create new scss file
- go inside src/assets/sass/light-bootstrap-dashboard.scss, and at the end of the file, import your new scss file
- add the following code inside your new scss file
```
footer.footer{
  position: relative;
  bottom: 0;
  width: 100%;
}
```
[new_file.scss.zip](https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/files/2777955/new_file.scss.zip)
I've also attached you the new file.

Hope this information helps you.

Best,
Manu
