### ISSUE TITLE
How to customer filter action Reactable 

### ISSUE THREAD

**Issue by thanhtungka91** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#31]
i dont want to use filter default because i have filter from server site, how can i customize it?
thanks

**Comment by einazare** [comment]
Hello there @thanhtungka91 ,

Thank you for your interest in working with our products.
Does the official documentation help you: https://react-table.js.org/#/story/readme
They have lots of examples.
Please take a look at the given link.

Best,
Manu
