### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by suarezhar** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#34]
Hi Creative Team,
Is this product compatible with Internet Explorer? 
Regards,
Harnier.

**Comment by einazare** [comment]
Hello there @suarezhar ,

Thank you for your interest in working with our product.
At the moment we do not offer support for Internet Explorer - it seems that we've forgotten to add this in our README.md. I'll add it in a few days.

Best,
Manu
