### ISSUE TITLE
Submenu and dynamic routes

### ISSUE THREAD

**Issue by zulfarrakk** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#36]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I've created a new parent route called "Projects" and I wanted to have sublevels with dynamic routes that will include in the URL the project code.

# Current Behavior

For sure I am doing something wrong, what I get is a redirect from my built URL to the Dashboard.

From
http://localhost:3000/projects/project1/detail/info
to
http://localhost:3000/projects/project1/detail/info#/dashboard

# Failure Information (for bugs)

None

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click on "Projects" entry in the sidebar
2. Click on a single project in "Projects" page
3. You will get redirected to dashboard

## Context

Inside the file "src/routes/dashboard.jsx"

I add the view import:

`import Projects from "views/Projects/Projects";`

and I created an entry for the Projects page:

`  {
    path: "/projects",
    name: "Projects",
    icon: "pe-7s-news-paper",
    component: Projects
  },`

The _Projects_ page is working fine and loading content correctly.
Inside this page I loop through my JSON and I render al the different project and I build the URL to a single project in this way:

`<a href={ 'projects/${this.props.code}/detail/info' }>
      <h4 className="title">{this.props.title}</h4>
</a>`

which return something like:
http://localhost:3000/projects/project1/detail/info

I changed the file  "src/routes/index.jsx" this way:

`import Pages from "layouts/Pages/Pages.jsx";
import Dashboard from "layouts/Dashboard/Dashboard.jsx";
import Project from "layouts/Project/Project.jsx";

var indexRoutes = [
  { path: "/pages", name: "Pages", component: Pages },
  { path: "/projects", name: "Projects", component: Dashboard },
  { path: "/project", name: "Project", component: Project },
  { path: "/", name: "Home", component: Dashboard }
];

export default indexRoutes;`

and I have created the file "src/routes/project.jsx" which contains:

`import ProjectInfo from "views/Project/Detail/Info.jsx";

var projectRoutes = [
  {
    path: "/project/:code/detail/info",
    name: "Info",
    mini: "IN",
    component: ProjectInfo
  }
];

export default projectRoutes;`

I created the file "src/layouts/Project/Project.jsx", making a copy&paste of "src/layouts/Dashboard/Dashboard.jsx", changing only these lines:

`import projectRoutes from "routes/project.jsx";`
`class Project extends Component {`
`{projectRoutes.map((prop, key) => {`
`export default Project;`

The file "src/views/Project/Detail/Info.jsx" contains basically nothing for now, just the h1 of the single Project page.

* Device: Laptop 15" no-touchscreen
* Operating System: Windows 10
* Browser and Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

## Failure Logs

None

**Comment by einazare** [comment]
Hello there, @zulfarrak ,

Sorry for this late response.
I can see that you are using `<a href=..`'s in your code, which is kind of a bad thing in a React app. You should use Link from react-router-dom. Here is a link about react-router-dom: https://reacttraining.com/react-router/web/guides/quick-start 
The second thing, for the dynamic routes to work, you will need to delete our redirects, and also, add the `exact` prop on all of the `<Route ...>` inside our app.
This problem was also addressed on one of our other products here: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/51

Hope this helps.

Best,
Manu

**Comment by zulfarrakk** [comment]
Hello @EINazare,

thanks for your response.

I modified the link, using the <Link> tag and the url genereated for each project now is something like:
`http://localhost:3000/#/projects/project1/detail/info`

I have modified the file "src/layouts/Project/Project.jsx" like this:

```
<Switch>
            {projectRoutes.map((prop, key) => {
              
              if (prop.redirect)
                return <Redirect from={prop.path} to={prop.pathTo} key={key} />;
              if (prop.collapse)
                return prop.views.map((prop, key) => {
                  return (
                    <Route path={prop.path} exact component={prop.component} key={key} />
                  );
                });
              return <Route path={prop.path} exact component={prop.component} key={key} />;
            })}
          </Switch>

```

using the code snippet from the other issue you suggested me (https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/51).

If I click on the new project url, it changes correctly in the url bar, but it's not working...

This is the file "src/views/Project/Detail/Info.jsx":

```
import React, { Component } from "react";
import { Grid, Row, Col } from "react-bootstrap";

class ProjectInfo extends Component {

  render () {
    return (
		<div className="content">
            <Grid fluid>
		        <Row>
		        
		        	<h1>Project Info</h1>
		            
		        </Row>
	        </Grid>
		</div>
    )
  }
}

export default ProjectInfo;
```


Am I doing something wrong with layout/wiews or with routes?

Many thanks for your support!

**Comment by einazare** [comment]
Hello again, @zulfarrak ,

The code seems ok to me.
What if you delete the redirect?
Meaning, that instead of:
```
if (prop.redirect)
                return <Redirect from={prop.path} to={prop.pathTo} key={key} />;
```
You say
```
if (prop.redirect)
                return null;
```

Sorry for my vague response, I haven't quite worked with dynamic routes.

Best,
Manu

**Comment by zulfarrakk** [comment]
Hello @EINazare,

Thanks for your help, it was very useful.

I was messing up a bit some other stuff also.
Here what I have done to make it work:

I changed:

```
var projectRoutes = [
  {
    path: "/projects/:code/detail/info",
    name: "Info",
    mini: "PIN",
    component: ProjectInfo
  },
  {
    path: "/projects/:code/detail/actions",
    name: "Actions",
    mini: "PAC",
    component: ProjectActions
  }
];
```
because I was missing a 's' inside the path (projects, not project) and I added other sub-pages for a single project.

I changed also this:

```
var indexRoutes = [
  { path: "/pages", name: "Pages", component: Pages },
  // { path: "/projects", name: "Projects", component: Dashboard },
  { path: "/projects/:code/*", name: "Project", component: Project },
  { path: "/", name: "Home", component: Dashboard }
];
```
commenting out the Projects line and adjusting the Project one with the asterisk because I will have multiple sub-pages (info, actions, ...).

In the end I want to point out that I am managing the current Project information (just the _code_ for now) with the React Context API (after upgrading react, react-dom and react-scripts).

Thanks again!
