### ISSUE TITLE
Yarn build error Lexical error on line 1: Unrecognized text

### ISSUE THREAD

**Issue by MerouaneBen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#37]
Hi , I'm trying to build a production version of the website. however this error : 
```
Wrote 1 CSS files to /app/src/
Creating an optimized production build...
Failed to compile.

Lexical error on line 1: Unrecognized text.
  Erroneous area:

1: 100% - $sidebar-width
^.........^
```

I tried to modify the `light-bootstrap-dashboard.css` file, I have changed  this line :
from this:
```
....  
.navbar.fixed {
    width: calc(100% - $sidebar-width); 
...
```
to this :

```
....  
.navbar.fixed {
    width: calc(100% - #{$sidebar-width}); 
...
```
but it didn't work. 

any idea about the issue. 

thanks,

**Comment by einazare** [comment]
Hello there @MerouaneBen ,

Thank you for your interest in working with our products.
Firstly, I would like to ask you, why did you not use our issues template:
```
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.
```

If I run `npm install && npm run build`, everything works as expected (please take a look at the bellow image).
<img width="1120" alt="Screen Shot 2019-03-29 at 11 00 34 AM" src="https://user-images.githubusercontent.com/26245512/55221607-84a7f700-5212-11e9-8765-d2bec0817eb7.png">

If you use `npm` instead of yarn, does the error still occurs? We haven't worked with `yarn`, and we've seen that there are some issues with `yarn` and our products, that is why in our live docs, we only say about `npm`, and not yarn.

Best,
Man

**Comment by MerouaneBen** [comment]
hi there @EINazare,

thanks for your quick reply, and sorry for not following the template you provided, I'll make sure to stick to template next time.

 well I have tested with both **YARN** and **NPM** and I get the same exact error. I managed to fix this problem  by editing the following file : **src/sass/lbd/_navbars.scss**  line 81 
from this
```
    &.fixed{
        width: calc(100% - $sidebar-width);
        right: 0;
        left: auto;
        border-radius: 0;
    } 
```
to this 
```
    &.fixed{
        width: calc(100% - #{$sidebar-width});
        right: 0;
        left: auto;
        border-radius: 0;
    }
```

it seems that when generating  the css  file, the compilation fails because of the variable without the curly braces `#{}` wrapping, this happens when there is a calculation function `calc(...)`

thanks,

**Comment by einazare** [comment]
Hello again, @MerouaneBen ,

Thank you for sharing with us your solution.
We'll add that in our product as well in the next update (please leave the issue opened).

Best,
Manu

**Comment by bogere** [comment]
I also faced the same error Lexical error ```
Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: 100% - $sidebar-width
I was able to resolve most of lexical error problems  by applying the `#{$variable} `in most parts
`#{$sidebar-width}           calc(100% - 260px) !default;`
yes but now i get this error
```
Invalid CSS after "... 54px !default;": expected 1 selector or at-rule, was "#{$sidebar-width}: "
in D:\node4\projectz\react_stuff\react_lessons\mobx\bizwatch_latest_react\src\assets\sass\lbd\_variables.scss (line 129, column 45)
```

**Comment by einazare** [comment]
> `#{$sidebar-width} calc(100% - 260px) !default;`

You should not change the variable default. Only this line `100% - $sidebar-width` with ` 100% - #{$sidebar-width}`

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

**Comment by bugger16** [comment]
I found the same problem in Black Dashboard PRO Angular
and can't fix it. Could you please help me.

**Comment by einazare** [comment]
Hello there, @bugger16 ,

Search for `width: calc(100% - $sidebar-width);` in your project and change it with `width: calc(100% - #{$sidebar-width});`.

Best,
Manu

**Comment by bugger16** [comment]
Hi Nazare,

I use ct-black-dashboard-pro-angular
<https://github.com/creativetimofficial/ct-black-dashboard-pro-angular>,
version 1.1.1 and not found calc(100% - $sidebar-width) in the project.

[image: Screen Shot 2563-04-21 at 19.09.37.png]

Best,
Kulrapat J.

**Comment by tendomart** [comment]
Can some one please create a PR and  have this issue merged.It prevents builds and hence deployment to demo/ production servers.

**Comment by tendomart** [comment]
But thanks a bunch guys.This small Bug was gon make me do a complete over-haul of a weeks work and consider other options.For some unknown reason , there is not much Error Search optimisation for This project .

**Comment by dreamyguy** [comment]
For those still getting here by googling **lexical error**, I came across something that might interest you... I have the following:

**Error message:**

```
Lexical error on line 1: Unrecognized text. Erroneous area:
1: 0, 20px
^...^
CompileError: Begins at CSS selector undefined
```

**Searching for `0, 20px` returned no matches.** The problem here is that there's a SCSS variable with the `20px` value, and that variable is not escaped with `#{}` within a CSS/SCSS function. I.e.:

**_variables.scss**

```
$base-font-size: 20px;
```

**_helpers.scss**

```
$result: rem-calc(nth($space-values, $i), $base-font-size)
```

**TLDR; always check for SCSS having the value(s) the lexical error outputs.**

**Comment by ejtooom** [comment]
> For those still getting here by googling **lexical error**, I came across something that might interest you... I have the following:
> 
> **Error message:**
> 
> ```
> Lexical error on line 1: Unrecognized text. Erroneous area:
> 1: 0, 20px
> ^...^
> CompileError: Begins at CSS selector undefined
> ```
> 
> **Searching for `0, 20px` returned no matches.** The problem here is that there's a SCSS variable with the `20px` value, and that variable is not escaped with `#{}` within a CSS/SCSS function. I.e.:
> 
> **_variables.scss**
> 
> ```
> $base-font-size: 20px;
> ```
> 
> **_helpers.scss**
> 
> ```
> $result: rem-calc(nth($space-values, $i), $base-font-size)
> ```
> 
> **TLDR; always check for SCSS having the value(s) the lexical error outputs.**

Hey, I have 

> For those still getting here by googling **lexical error**, I came across something that might interest you... I have the following:
> 
> **Error message:**
> 
> ```
> Lexical error on line 1: Unrecognized text. Erroneous area:
> 1: 0, 20px
> ^...^
> CompileError: Begins at CSS selector undefined
> ```
> 
> **Searching for `0, 20px` returned no matches.** The problem here is that there's a SCSS variable with the `20px` value, and that variable is not escaped with `#{}` within a CSS/SCSS function. I.e.:
> 
> **_variables.scss**
> 
> ```
> $base-font-size: 20px;
> ```
> 
> **_helpers.scss**
> 
> ```
> $result: rem-calc(nth($space-values, $i), $base-font-size)
> ```
> 
> **TLDR; always check for SCSS having the value(s) the lexical error outputs.**

I'm stuck and I bumped on your post, looked for it some time to solve this and I fugured out that this lines make it:

custom.scss

    $link-decoration: none;
    $link-hover-decoration: none;
    
    $border-radius: 0;
    
    $card-border-width: none;
    
    $btn-border-radius-lg: 0;
    $btn-border-radius-sm: 0;
    
    @import '~bootstrap/scss/bootstrap.scss';

When I run build, it fails because of Lexical error on line 1: Unrecognized text. Erroneous area: 1: 0 - none.  


    -----> Build
           Running build
           
           > ecommerce-store@1.0.0 build
           > cd frontend && npm install && npm run build
           
           
           added 1951 packages, and audited 1952 packages in 54s
           
           129 packages are looking for funding
             run `npm fund` for details
           
           found 0 vulnerabilities
           
           > frontend@0.1.0 build
           > react-scripts build
           
           Creating an optimized production build...
           Failed to compile.
           
           Lexical error on line 1: Unrecognized text.
             Erroneous area:
           1: 0 - none
           ^......^
           CompileError: Begins at CSS selector undefined
           
           
    npm ERR! code 1
    npm ERR! path /tmp/build_5c229236/frontend
    npm ERR! command failed
    npm ERR! command sh -c react-scripts build
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /tmp/npmcache.GNGeo/_logs/2021-02-08T20_27_19_656Z-debug.log
    npm ERR! code 1
    npm ERR! path /tmp/build_5c229236
    npm ERR! command failed
    npm ERR! command sh -c cd frontend && npm install && npm run build
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /tmp/npmcache.GNGeo/_logs/2021-02-08T20_27_19_675Z-debug.log
    -----> Build failed
           
           We're sorry this build is failing! You can troubleshoot common issues here:
           https://devcenter.heroku.com/articles/troubleshooting-node-deploys
           
           If you're stuck, please submit a ticket so we can help:
           https://help.heroku.com/
           
           Love,
           Heroku
           
     !     Push rejected, failed to compile Node.js app.
     !     Push failed


Can anyone help me? Thank you
