### ISSUE TITLE
How to use it with Laravel

### ISSUE THREAD

**Issue by aleemzada** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#38]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by aleemzada** [comment]
Any one have tuts etc ?

**Comment by einazare** [comment]
Hello there @aleemzada ,

Thank you for your interest in working with our products.
At the moment we haven't used Laravel with our ReactJS products and can't really give you any guidance from our experience.
We can only give you tutorials from YouTube or Google that may or may not work with our product.
Here are some links found YouTube and Google:
https://appdividend.com/2017/08/31/laravel-5-5-reactjs-tutorial/
https://developer.okta.com/blog/2018/12/06/crud-app-laravel-react
https://blog.pusher.com/react-laravel-application/

https://www.youtube.com/watch?v=WYKSDrgk0fE&list=PLTXFz3WKxvNJZo1T0-ypVBWD0MfJtshav
https://www.youtube.com/watch?v=XJ6E9-YdGJU&list=PLS28RXxLK_RRh5y0vwkL2CFVpyjwd_oyy
https://www.youtube.com/watch?v=HPobijkTJAI

Best,
Manu
