### ISSUE TITLE
Bug on the website

### ISSUE THREAD

**Issue by Hansander** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#39]
Hi there,

There seems to be a bug on the Components/Panels screen of the Live Preview. Once a user clicks on anything on the screen, the entire screen goes white.

https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/?_ga=2.192861994.1078862990.1557728116-1224636826.1551362841#/admin/panels

**Comment by einazare** [comment]
Hello there, @Hansander ,

I think we've spoken on the contact-us form.
Sorry for not being clear enough. When I asked you to open a Github issue here, I forgot to mention that you should use our ISSUES_TEMPLATE as well.
Please use our issues template whenever you open an issue on our repositories:
```
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

```
As you can see in the below image, everything works fine.
If you use our ISSUES_TEMPLATE you will have to give us some steps to reproduce your issue, also, tell us what operating system do you use, browser etc.
The issue you are experiencing may be something just on some types of browsers etc.

![lbd-pro-react-support](https://user-images.githubusercontent.com/26245512/57602412-b0cfcb00-7567-11e9-844c-be77f327dfd7.gif)

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by Hansander** [comment]
Hi Sorry, I do not know what happened, it seems to be working now.  I merely reported what I saw.  It is fixed now...technology...what can you do?
