### ISSUE TITLE
Bug on website Fixed header with Sidebar Mini

### ISSUE THREAD

**Issue by Hansander** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#40]
Hi There,

I noticed this error while reviewing your template.  When the configuration is done on this page
https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/?_ga=2.192861994.1078862990.1557728116-1224636826.1551362841#/admin/dashboard

that the sidebar mini is selected together with the Fixed Navbar, there is a gap between the Navbar and the Sidebar and the Navbar covers the content on the page.  

![image](https://user-images.githubusercontent.com/29998695/57601947-2767cb00-755e-11e9-8911-7c3185d55fde.png)

**Comment by einazare** [comment]
Hello there, @Hansander ,

I think we've spoken on the contact-us form.
Sorry for not being clear enough. When I asked you to open a Github issue here, I forgot to mention that you should use our ISSUES_TEMPLATE as well.
If you use our ISSUES_TEMPLATE you will have to give us some steps to reproduce your issue, also, tell us what operating system do you use, browser etc.
The issue you are experiencing may be something just on some types of browsers etc.
Please use our issues template whenever you open an issue on our repositories:
```
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

```

This being said, the solution for the above issue is to add the following css/scss:
```
.sidebar-mini .main-panel .navbar-fixed {
    width: calc(100% - 80px);
}
```
Please leave the issue opened.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

**Comment by mosolini** [comment]
I am facing the same issue descriped here. Adding to that when the Nav bar is fixed, the dashboard cards go behind it as shown in the original bug description. Is there any fix introduced for this issue ?

**Comment by einazare** [comment]
> I am facing the same issue descriped here. Adding to that when the Nav bar is fixed, the dashboard cards go behind it as shown in the original bug description. Is there any fix introduced for this issue ?

Hello there, @mosolini ,

Please read my comment: https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/issues/40#issuecomment-491704366

Best,
Manu

**Comment by mosolini** [comment]
Thanks a lot @EINazare

**Comment by einazare** [comment]
Hello again, @mosolini ,

Glad it was of help.

Happy Hacking!

Best,
Manu
