### ISSUE TITLE
[Feature Request] Got bootstrap 3 instead of bootstrap 4.

### ISSUE THREAD

**Issue by NabinKhatiwada** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#43]
### What is your enhancement?
We purchased this template for our project recently. Everything is cool except, template is done in bootstrap 3 which is quite old and we are not familiar with 3. Is there any update for bootstrap 4 coming that we can download without paying additional fee for the same theme anytime soon?

**Comment by einazare** [comment]
Hello there, @NabinKhatiwada ,

Thank you for your interest in working with our product.
At the moment we do not have a timeline for this.
I will forward your request to our board and I will do my best to make it happen by the end of September - right now we are making some updates to our Material products.

Best,
Manu

**Comment by NabinKhatiwada** [comment]
Thank you for your response. We will be very happy to work with latest bootstrap.

**Comment by MinasA1** [comment]
Hi @EINazare ,

Any updates on usage of bootstrap 4?

Best,
Minas

**Comment by einazare** [comment]
Hello again, @MinasA1 ,

Unfortunately, the Creative Tim board decided to skip again this product on updating to Bootstrap 4.

Best,
Manu
