### ISSUE TITLE
Row and Column settings for textarea is not working

### ISSUE THREAD

**Issue by ruegreen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#44]
I am trying to use the following code block:

`<FormControl
       id="Text"
       componentclassName="textarea"
       rows="5"
       name="text"
       placeholder="My text"
       value={this.state.Text}
       onChange={event => this.setState({Text: event.target.value})}
    />
{this.state.TextError}`

This is from LBD Pro React product.  However, I cannot get a 5 row textarea to appear.  Is there something I should be doing different to create a multi-line textarea?  It looks like the textarea props are being ignored??

**Comment by einazare** [comment]
Hello there, @ruegreen ,

It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/light-bootstrap-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```

All the best,
Manu
Developer @ [Creative-Tim.com](http://creative-tim.com/)
