### ISSUE TITLE
[Bug] Trying to get a multi-line text area to render

### ISSUE THREAD

**Issue by ruegreen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#45]
### Version
v1.1.0
### Reproduction link
http://why.notapplicable.com
### Operating System
Mac OSX
### Device
laptop
### Browser & Version
all browsers
### Steps to reproduce
I am trying to use the following code block:

<FormControl id="Text" componentclassName="textarea" rows="5" name="text" placeholder="My text" value={this.state.Text} onChange={event => this.setState({Text: event.target.value})} /> {this.state.TextError}

This is from LBD Pro React product. However, I cannot get a 5 row textarea to appear. Is there something I should be doing different to create a multi-line textarea? It looks like the textarea props are being ignored??

### What is expected?
I would like a multi-line text area like what I am currently typing in but I get a single line.
### What is actually happening?
Single ling and not multi-line text area

---
### Additional comments
Update you documentation to provide better examples of how this stuff can be accomplished, this should be an easy thing to do and I hope its just me...

**Comment by einazare** [comment]
Hello there, @ruegreen ,

Thank you for your interest in working with our products.
We have an example of that here: https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/admin/user-page
The file is located here: `src/views/Pages/UserPage.jsx`.
Please note that this is not actually a bug, but an enhancement or help wanted.

Best,
Manu

**Comment by ruegreen** [comment]
Actually disagree with you, your own documentation is wrong and that’s why in my request I noted it as a document bug.  Here is why:
Looking at your own documentation found here: https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/textarea

You noted that you support the following:  componentclassName="textarea"
However, your example (thanks for pointing me to it), does not use componentclassName="textarea" but instead it uses componentclass="textarea".

If you use the one found in your own documentation you get a single line text area and the rows prop is completely ignored.  Maybe you need to update your documentation and file this as a documentation bug or figure out why componentclassName noted in your documentation does work.

Thanks for the help but I would like to see your documentation accurate to avoid hours of trying to figure out why something is not working as noted.

Cheers,

-Rue Green

**Comment by einazare** [comment]
Hello again, @ruegreen 

I've just updated the live docs.
If the changes do not show immediately, this means that your browser has cached that page, try using incognito mode or another browser.

Best,
Manu
