### ISSUE TITLE
[Bug] How to tell what size of client screen I am using and conditionally set content in render?

### ISSUE THREAD

**Issue by ruegreen** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#47]
### Version
1.1.0
### Reproduction link
https://consent.gurueconsulting.com
### Operating System
MAC
### Device
Laptop
### Browser & Version
All
### Steps to reproduce
Not really a bug but looking for help on how I can tell in say the dashboard view main main content card what size of screen I am on.  I want to drop some logos and other stuff to keep the viewing experience on a phone good for the dashboard.  IS there a way to tell what size of screen I am on..ie phone etc.  and is there a way to shrink images to fit within the grid setting I have for that screen size...like XS grid size...but my image inside that tag is over running the card size.
### What is expected?
should be a way to set image sizes to match the grid size used on a card for example.
### What is actually happening?
image in a card .. viewed on smaller screen is not scaling correct

---

**Comment by einazare** [comment]
Hello again, @ruegreen ,

This is fairly simple, you just need to use the `window.innerWidth` to get the width of the device that you are on.
Something like:
```
{
      window.innerWidth > 991 ? (
             ...do something here if the window has a width larger then 991
      ):(
             ...do something else here if the window has a width smaller or equal to 991
      )
}
```

Hope that helped.

Best,
Manu

**Comment by ruegreen** [comment]
Ok can you advise me on what widths you use for your grid setup, in other words what do MD, XS, etc. match for min and max widths?  The one I am having issues with is the XS for dynamic sizing on an iphone which seems to use the XS grid setting, what have you defined XS for dimensions of screen?  Also, is there a way to automatically size an image, ie shrink it to fit when I am on a grid that is much smaller than say MD ?

**Comment by einazare** [comment]
Hello again, @ruegreen ,

We use the same widths as Bootstrap 3 Grid.
Here is a link: https://getbootstrap.com/docs/3.3/css/#grid

Best,
Manu
