### ISSUE TITLE
Upgraded Bootstrap 4 due to XXS 

### ISSUE THREAD

**Issue by morf-code** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#48]
### Version
 "version": "1.2.0",
### Reproduction link
https://github.com/murffious
### Operating System
Mac OS Catalina
### Device
MacBook PRo
### Browser & Version
Chrome latest
### Steps to reproduce
npm install 
npm install fsevents@latest core-js@latest
npm audit fix 
npm install bootstrap@4.3.1
npm run start
open browser on a 27 inch screen 

this is due to the security issue of xxs noted in the npm logs 
### What is expected?
look like your site example 
### What is actually happening?
looks like crap not responsive

---
### Solution
manually fix if i Can or use other template sadly

**Comment by einazare** [comment]
Hello there, @morf-code ,

Thank you for your interest in working with our products.
At the moment, this product only works with BS3.
Do not change the BS version.

Best,
Manu
