### ISSUE TITLE
[Bug] Broken import inside AdminNavbar.jsx

### ISSUE THREAD

**Issue by darsenault** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#49]
### Version
1.2.0
### Reproduction link
http://paying-customer-please-fix.com
### Operating System
OSX
### Device
Macbook
### Browser & Version
Safari 13.0.4
### Steps to reproduce
import AdminNavbar from './components/Navbars/AdminNavbar.jsx';
or
import Sidebar from './components/Sidebar/Sidebar.jsx';
### What is expected?
Not throwing an import error when attempting to use of the the paid components, following the documentation's guidance.
### What is actually happening?
./src/components/Navbars/AdminNavbarLinks.jsx
Attempted import error: 'MenuItem' is not exported from 'react-bootstrap'.

MenuItem is an import in Navbars/AdminNavbar.jsx

---

**Comment by einazare** [comment]
Hello there, @darsenault ,

Thank you for your interest in working with our products.
Please provide me with your package.json file.
I have one more question, the link you have provided does not work, was this intentional?

Best,
Manu
