### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by einazare** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#5]
For RTL you need to follow these steps:

1. Add in `public/index.html` file this line `<link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">` inside the `<head>...</head>` tags.
2. Replace `<body class="off-canvas-sidebar">` with `<body class="off-canvas-sidebar rtl-active">` inside the `public/index.html` file.
3. Download this file
[lbdp_rtl.scss.zip](https://github.com/creativetimofficial/lbd-pro-react/files/1618140/lbdp_rtl.scss.zip)
4. Unzip the file.
5. Add the unzipped file in `src/assets/sass/lbd/` folder.
6. Add this line `@import "lbd/lbdp_rtl";` at the end of the `src/assets/sass/light-bootstrap-dashboard.scss` file.

**Comment by emadaaltiti** [comment]
there  is bugs  when i follow your steps look it to this screen  
Look
![image](https://user-images.githubusercontent.com/25552526/35505855-19e941b4-04f0-11e8-9918-408a8fec7939.png)
![image](https://user-images.githubusercontent.com/25552526/35506016-a383d704-04f0-11e8-9abb-2d0b0196af03.png)
![image](https://user-images.githubusercontent.com/25552526/35506074-cf8406b2-04f0-11e8-8a11-6981b82b1f7b.png)

**Comment by einazare** [comment]
Hello @emadaaltiti ,

This is caused by the perfect-scrollbar plugin.
To stop it from doing so, please replace 
`Ps.initialize(this.refs.mainPanel, { wheelSpeed: 2, suppressScrollX: true });`
with
`Ps.initialize(this.refs.mainPanel, { wheelSpeed: 2, suppressScrollX: true, suppressScrollX: false });`

This is located in:
- `src/containers/Dash/Dash.jsx` line 34

Best,
Manu

**Comment by emadaaltiti** [comment]
@EINazare  
thanks a lot ,
i have another question 
i used react-intl to support multiple language 
i need to make everything rtl when Login in  if chose Arabic ltr if chose English
everything work fine except sidebar and Dashboard 
do you have any solution for that maybe import different css file for Arabic or English

thanks again

**Comment by einazare** [comment]
When choosing English, to stop using RTL, you should delete the `rtl-active` class from the body tag and you should also delete the `<link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">` from the index.html page.
If you are having trouble with this, let me know.

All the best,
Manu

**Comment by dreamcode-star** [comment]
Hello einazare, how are you?
I'm a web developer and building a university management dashboard using this theme.
I need to implement multi-language support, and in fact the way you explained is not clear to me.
I'm sorry for that, but could you please write a tutorial to implement that in your theme?
Thanks a lot.

christopher.
