### ISSUE TITLE
[Bug] DropdownButton & screen less 992px

### ISSUE THREAD

**Issue by ARdmr** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#50]
### Version
1.2.0
### Reproduction link
https://www.creative-tim.com/product/light-bootstrap-dashboard-pro-react
### Operating System
macOS
### Device
Mac
### Browser & Version
Chrome, Safari, etc
### Steps to reproduce
1. Put Dropdown (https://react-bootstrap-v3.netlify.app/components/dropdowns/#btn-dropdowns).
2. Use screen < 992px.
### What is expected?
Dropdown looks normal.
### What is actually happening?
DropDown is corrupted.

---

**Comment by einazare** [comment]
Hello there, @ARdmr ,

Please go inside this file: src/assets/sass/lbd/_responsive.scss
And change line 669 from `  .open .dropdown-menu {` to `  .navbar .open .dropdown-menu {`.

Best,
Manu

**Comment by ARdmr** [comment]
It works, thanks!

**Comment by ARdmr** [comment]
> Hello there, @ARdmr ,
> 
> Please go inside this file: src/assets/sass/lbd/_responsive.scss
> And change line 669 from ` .open .dropdown-menu {` to ` .navbar .open .dropdown-menu {`.
> 
> Best,
> Manu

Unfortunately, it breaks NavDropdown in sidebar in "<= 992" mode.

**Comment by einazare** [comment]
Hello again, @ARdmr ,

Please change the following code:
```
  .open .dropdown-menu {
    position: static;
    float: none;
    width: auto;
    margin-top: 0;
    background-color: transparent;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
```
To:
```
  .navbar,.sidebar{
      .open .dropdown-menu {
      position: static;
      float: none;
      width: auto;
      margin-top: 0;
      background-color: transparent;
      border: 0;
      -webkit-box-shadow: none;
      box-shadow: none;
    }
  }
```

Best,
Manu
