### ISSUE TITLE
[Bug] dependencies not updated

### ISSUE THREAD

**Issue by Darkzone1** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#53]
### Version
1
### Reproduction link
https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/issues/52
### Operating System
Windows y linux
### Device
Laptop
### Browser & Version
Chrome 85.0.4183.102
### Steps to reproduce
creation of a new project in react
copy the SRC directory to the new project
Install updated dependencies
run the npm start
### What is expected?
to update the dependencies of the themes ..., so that they do not generate errors when integrating them
### What is actually happening?
the dependencies of the theme are not updated .., and when integrating and compiling it generates many errors !!!

---
### Solution
to update the dependencies of the themes ..., so that they do not generate errors when integrating them
### Additional comments
I take care that the themes that they provided me in the pro version .., are updated with the versions of the most current dependencies

**Comment by Darkzone1** [comment]
![WhatsApp](https://user-images.githubusercontent.com/6607097/93542901-db7e2080-f91f-11ea-9c5d-b215034ee250.jpeg)

**Comment by einazare** [comment]
Hello there, @Darkzone1 ,

Please revert the changes and wait for our updates, they are going to be done by the end of this year.

Best,
Manu
