### ISSUE TITLE
[Bug] npm ERR! Could not resolve dependency: peer react@"^16.6.1" from react-big-calendar@0.30.0

### ISSUE THREAD

**Issue by vchong88** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#56]
### Version
2.0
### Reproduction link
https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react
### Operating System
MacOS
### Device
Macbook Pro
### Browser & Version
Chrome
### Steps to reproduce
Step 1: Download the new version 2.0 from Creative Tim website
Step 2: Extract zip file
Step 3: npm install
### What is expected?
No npm ERR
### What is actually happening?
There is npm error whereby dependency is unable to install

---

**Comment by einazare** [comment]
Hello there, @vchong88 ,

We've just tested the product and it seems to work as expected.
Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Will wait for the mentioned video.

Best,
Manu

**Comment by vchong88** [comment]
Hi @EINazare,

Thank you for taking up my case. Please find the link to the video. https://youtu.be/Fj-Zsx-Drfk

Thank you & Stay Safe.

Best Regards,
Patrick

**Comment by einazare** [comment]
Hello again, @vchong88 ,

Thank you for the video.
To solve the issue, you just need to go here: https://nodejs.org/en/
After that, you will have to download and install the NodeJS version **14.15.4 LTS**.
Unfortunately, our products only work with LTS versions of NodeJS due to the dependencies that we have.

I've just updated the documentation here: https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/tutorial and replaced 
```
Install NodeJs from NodeJs Official Page
```
With
```
Install NodeJS LTS version from NodeJs Official Page (NOTE: you need the LTS version, as our product only works with LTS version)
```

Best,
Manu

**Comment by felgoulart** [comment]
I´ve the same problem: node -v: v14.16.1 LTS / npm-v: 7.10.0 / windows 10. I did the downgrade to node 14.15.4 LTS and the problem still occurring.

**Comment by einazare** [comment]
Hello there, @vchong88 ,

Please download and install NodeJS LTS version from the official website: https://nodejs.org/en/
Also, after you do that, please do not change the version of `npm` that NodeJS LTS version comes with.
On my machine it looks like this:
<img width="235" alt="Screen Shot 2021-05-10 at 9 07 04 AM" src="https://user-images.githubusercontent.com/26245512/117613152-18c54600-b16f-11eb-9b35-716243ecce4b.png">

Best,
Manu

**Comment by simonhsu** [comment]
$ node -v
v14.16.1
$ npm -v
8.4.0

also shows so many npm ERR! s
please help

**Comment by simonhsu** [comment]
finally worked, I've just uninstall all node&npm , and then use nvm & nvm install 14
