### ISSUE TITLE
[Bug] not sure how to activate sidebar Admin/My Profile link

### ISSUE THREAD

**Issue by mr-miner** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#59]
### Version
v2
### Reproduction link
https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/admin/react-table
### Operating System
mac
### Device
macbook
### Browser & Version
safari 14.0.1
### Steps to reproduce
In the example dashboard, the links for the Admin My Profile, Edit Profile, and Settings don't have click actions.

### What is expected?
I'd like clicking these to do roughly the same thing is clicking other links in the sidebar: the component loads with the Admin layout.
### What is actually happening?
When trying to add clickable actions to the My Profile, Edit Profile, and Settings, I can't seem to get the layout to load.

---
### Solution
I have a component that I'd like to route those clicks to, but because they don't appear in the routes.js array, the routing isn't recognized.  I've tried random ideas in my App.js where the main Routes are declared, for example, adding a line like this:

<Route exact path="/admin/profile" component={AdminWrapper} layout={"/admin"} render={(props) => <Admin {...props} />} />

Which gets it close, it does try to load the component, but it won't load the layout.  Are there instructions for how to do this?  I can't seem to find.  Thanks.

**Comment by sajadevo** [comment]
**Hi @mr-miner**

There are just samples you can add the routes you like to have for those links:

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
