### ISSUE TITLE
login / register assistance

### ISSUE THREAD

**Issue by lacoursj** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#6]
Hello,

I am new to React and NodeJS, and have been struggling for a few weeks to understand this template and how to use the components to create our app.  Can you point me to any reasonable tutorials that will help me get login and registration working given your template's layout?  Most of what I can find online utilizes "express" or other additions and the examples don't match your layout at all.  For registration, for example, I would like to post the form data to something server side that will process the fields and enter into a database.  I can't figure out how to specify a route for the target of the POST.  Express examples assume that express was loaded in server.js, which doesn't seem to exist when I am using "npm start", so I am confused about where to load express, body-parser, etc.  If I make the target match a current route, like "/pages/login-page", I get an error that I can't post to that route.  I rarely throw up my hands and ask for assistance, but I must be missing something very basic.  Can you point me in a direction?

Thanks!

**Comment by einazare** [comment]
Hello @lacoursj ,

and thank you for using our product. For this issue i would recommend you to use ajax ([see this tutorial here](https://www.w3schools.com/xml/ajax_intro.asp) - if ajax with pure javascript is harder to understand you can use ajax with jQuery instead, but i would recommend not to use jQuery for other stuff while using react, [jQuery ajax tutotiral](http://api.jquery.com/jquery.ajax/)). Further more, i would recommend you to have two applications: 
1. one would be the front-end application, the user interface - i.e. our template
2. and one would be the back-end application, this one would have some scripts which would return data from your database  based on what you would request with your ajax call

This ajax calls could be put in the _send button action_ (`onClick`) of the login/register form.

Another way around is to use, as you've said `Express.js`, but from my research that would mean to make huge changes to our template. I see that `Express.js` uses a different routing scheme, and you would have to change all our routes.

From what i've seen, i would choose to go with the first option, ajax calls to a server-side application.
I hope this information helps you and if you have any other questions, we are here to help you.

All the best, Manu

**Comment by lacoursj** [comment]
Ok, that makes sense though disappointing.  I am familiar with AJAX in pure JS, and have always done my backends with PHP, so I can make that work.  I was really hoping to do everything in react/node :)

Is it reasonable to put the backend under public, and make public the doc root of an apache site conf? To at least keep all the files in one place?

Thanks,

j

**Comment by einazare** [comment]
Not sure if that would work, but you can try it.

**Comment by shailendrasdl** [comment]
Hello,
 
I m using The Light Bootstrap Dashboard with React  admin panel
 How to set Login page first then Move to dashboard Route
i m try to { path: "/", name: "Home", component: Pages} 
dashboard  page is redirect But inside page in not Move (route)  plz help

**Comment by einazare** [comment]
Hello there @shailendrasdl ,

Thank you for your interest in working with our products.
Delete all the changes made by you. Revert everything back to the original form.
Then go inside `src/routes/dashboard.jsx` and change line
```
{ redirect: true, path: "/", pathTo: "/dashboard", name: "Dashboard" }
```
to
```
{ redirect: true, path: "/", pathTo: "/pages/login-page", name: "Dashboard" }
```

Best,
Manu
