### ISSUE TITLE
[Bug] Radio buttons messed up on windows

### ISSUE THREAD

**Issue by jyte** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#60]
### Version
2.0.0
### Operating System
Windows
### Device
PC
### Browser & Version
edge / chrome / firefox
### Steps to reproduce
- Unzip the template archive light-bootstrap-dashboard-pro-react-v2.0.0.zip
- run : npm install
- run : npm start

On a *windows* computer, open chrome/edge/firefox and navigate to the "From / Regular Forms" menu.
### What is expected?
Radio buttons are nice circles
### What is actually happening?
radio buttons are messy square.

---
### Additional comments
It works fine with with chrome/firefox on linux...

chrome/edge windows
![Screenshot_20211022_110505](https://user-images.githubusercontent.com/7738906/138475492-d297a406-b51b-4edb-91a5-4ac832c48cad.png)

firefox windows
![Screenshot_20211022_110354](https://user-images.githubusercontent.com/7738906/138475585-dea1910d-2cec-426f-b43c-26c8c08c0367.png)

Chrome/firefox linux
![Screenshot_20211022_110534](https://user-images.githubusercontent.com/7738906/138475673-e957f155-d3b6-433a-af22-e1ed4b4ccd83.png)

**Comment by sajadevo** [comment]
**Hi @jyte**

We've just updated the product please double check this and if you have the same issue please lemme know.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
