### ISSUE TITLE
[Bug] Last Column Border of Striped Table with Hover Table is not straight

### ISSUE THREAD

**Issue by vchong88** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#61]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/?_ga=2.151316153.1288554220.1637805712-1517956235.1636039129#/admin/regular-tables
### Operating System
macOS Big Sur
### Device
Macbook Pro
### Browser & Version
Chrome & Safari
### Steps to reproduce
1. Navigate to the link (Tables -> Regular Tables)
2. Border of last column of "Striped Table with Hover" table is not straight.

Notice happened to other tables as well. eg. Regular Table with Colors, Extended Tables (Table with Switches)

### What is expected?
Straight line
### What is actually happening?
CSS requires fixing

---

**Comment by sajadevo** [comment]
**Hi @vchong88**

Its not a bug it's a UI case that we've added an extra space at the end.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
