### ISSUE TITLE
[Feature Request] Horizontal scroll for react-table

### ISSUE THREAD

**Issue by IlyasPatel** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#64]
### What is your enhancement?
Do you have an example how I could add horizontal scroll on react-table please?

**Comment by sajadevo** [comment]
**Hi @IlyasPatel**

We've used [React Table](https://react-table.tanstack.com/) please use its documentation for more info.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
