### ISSUE TITLE
react router dom

### ISSUE THREAD

**Issue by Kittinutz** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#7]
how can i protect router in this template sir

**Comment by einazare** [comment]
Hello @knightza123 ,

And thank you for your interest in our product.
I am not sure what do you mean by 

> protect router

, but i think these following links will help you in this matter:

- [Protected Routes](https://tylermcginnis.com/react-router-protected-routes-authentication/)
- [React-Router Github](https://github.com/ReactTraining/react-router/issues/4489)
- [Stackoveflow](https://stackoverflow.com/questions/43164554/how-to-implement-authenticated-routes-in-react-router-4)

I hope that is what you were looking for and if we can help you please let us know.

All the best,
Manu
