### ISSUE TITLE
child containers do not scroll with mousewheel

### ISSUE THREAD

**Issue by seanmccay** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#8]
I think this is due to the use of perfect-scrollbar in Sidebar.jsx. 

If I have a child container like a Card and I set overflow to scroll, the scrollbars show up and everything, but I can't scroll vertically (horizontal scrolling works) with my mouse wheel. I have to click and drag the scrollbars. I've also noticed that perfect-scrollbar isn't applied to child containers, so they have default browser scrollbars.

What's causing this, how can I fix it, and how can I apply perfect-scroll to all containers?

Here's a GIF:
![scolling](https://user-images.githubusercontent.com/19294231/35300419-f34a1f84-004d-11e8-9697-b1ccd881039c.gif)

**Comment by einazare** [comment]
Hello @seanmccay ,

To add perfect-scrollbar for you component you need to add these in your component:
- a function to verify if you are not on a Mac machine (has to be somewhere in your component)
`isMac(){`
`        let bool = false;`
`        if (navigator.platform.toUpperCase().indexOf('MAC') >= 0 || navigator.platform.toUpperCase().indexOf('IPAD') >= 0) {`
`            bool = true;`
`        }`
`        return bool;`
`    }`
- the following code in your `componentDidMount` function (this is the initialization of the perfect-scrollbar)
`if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {`
`            Ps.initialize(#yourComponentSelectorHere, { wheelSpeed: 2, suppressScrollX: true, suppressScrollY: true });`
`        }`
- these imports 
`import * as Ps from 'perfect-scrollbar';`
`import 'perfect-scrollbar/dist/css/perfect-scrollbar.min.css';`
- `#yourComponentSelectorHere` has to be a selector on the container you want to add the scrollbar
- and in the `componentDidUpdate()` function this code:
` if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {`
          `  setTimeout(() => { Ps.update(this.refs.mainPanel) }, 350);`
     `   }`

In our demo, you will see the selector being a `ref` attribute (see lines 95, 78 to 80, 70 to 76, 33 to 35, 8 and 9 - in Dash component ( `src/containers/Dash/Dash.jsx` ))

As for why the mouse wheel scrolls horizontally, i will make some tests, and try to find out why is this happening and come back with an answer for this as well.

Best,
Manu

**Comment by seanmccay** [comment]
Ok, I'll try that out. 

Just to clarify, the horizontal scrolling was intentional. I was using `SHIFT + mouse wheel`. Just demonstrating that one direction works while the other doesn't.

**Comment by seanmccay** [comment]
I added perfect-scroll to the Card component and that took care of it. If someone wants a container on the page to be scrollable, I guess they'll have to add perfect-scroll to that component, or just stick it inside a modified Card.

Here's my modification of your Card component:
``` javascript
import React, { Component } from 'react';
// this is used to create scrollbars on windows devices like the ones from apple devices
import * as Ps from 'perfect-scrollbar';
import 'perfect-scrollbar/dist/css/perfect-scrollbar.min.css';

class Card extends Component{
    isMac(){
        let bool = false;
        if (navigator.platform.toUpperCase().indexOf('MAC') >= 0 || navigator.platform.toUpperCase().indexOf('IPAD') >= 0) {
            bool = true;
        }
        return bool;
    }
    componentDidMount(){
        if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {
            Ps.initialize(this.refs.cardContainer, { wheelSpeed: 2, suppressScrollX: false });
        }
        if (this.props.descending) {
            this.refs.cardContainer.scrollTop = this.refs.cardContainer.scrollHeight;
        }  
        if (this.props.ascending) {
            this.refs.cardContainer.scrollTop = 0;
        }  
    }
    componentDidUpdate(e){
        if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {
            setTimeout(() => { Ps.update(this.refs.cardContainer) }, 350);
        }    
        if (this.props.descending) {
            this.refs.cardContainer.scrollTop = this.refs.cardContainer.scrollHeight;
        }  
        if (this.props.ascending) {
            this.refs.cardContainer.scrollTop = 0;
        }   
    }
    render(){
        return (
            <div id={this.props.id ? this.props.id : ""} ref="cardContainer"
                className={"card"
                    + (this.props.hidden ? " card-hidden":"")
                    + (this.props.calendar ? " card-calendar":"")
                    + (this.props.plain ? " card-plain":"")
                    + (this.props.wizard ? " card-wizard":"")
                    + (this.props.success ? " card-success":"")
                    + (this.props.info ? " card-info":"")
                    + (this.props.warning ? " card-warning":"")
                    + (this.props.danger ? " card-danger":"")
                    + (this.props.scrollable ? " card-scrollable":"")
                }                
                style = {{
                    maxHeight: this.props.maxHeight ? this.props.maxHeight : "",
                    overflow: this.props.scrollable ? "scroll" : "visible"
                }}              
            >                
                {
                    (this.props.title !== undefined) || (this.props.category !== undefined) ?
                    (
                        <div className={"header" + (this.props.textCenter ? " text-center":"")}>
                            <h4 className="title">{this.props.title}</h4>
                            <p className="category">{this.props.category}</p>
                        </div>
                    ):""
                }
                {
                    (this.props.tools) ?
                    (
                        <div className="card-tools pull-right">
                            {this.props.tools}
                        </div>
                    ):""
                }
                <div className={"content"
                    + (this.props.ctAllIcons ? " all-icons":"")
                    + (this.props.ctFullWidth ? " content-full-width":"")
                    + (this.props.ctTextCenter ? " text-center":"")
                    + (this.props.tableFullWidth ? " table-full-width":"")}>
                    {this.props.content}
                </div>
                {
                    (this.props.stats !== undefined) || (this.props.legend !== undefined) ? (
                        <div className={"footer"
                            + ( this.props.ftTextCenter ? " text-center":"" )
                            + (this.props.fixedFooter ? "fixed" : "") }>
                            {this.props.legend !== undefined ? (
                                <div className="legend">
                                    {this.props.legend}
                                </div>
                            ):null}
                            {this.props.stats !== undefined ? (<hr />):null}
                            {this.props.stats !== undefined ? (
                                <div className="stats">
                                    {this.props.stats}
                                </div>
                            ):null}
                        </div>
                    ):null
                }
            </div>
        );
    }
}

export default Card;

```

**Comment by einazare** [comment]
Happy to hear that everything works now.
